language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t yogeshverma1/docker-react-complex -f ./client/Dockerfile.dev ./client

# script:
#   - docker run yogeshverma1/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true yogeshverma1/docker-react-complex npm test

after_success:
    - docker build -t yogeshve1/complex-client ./client
    - docker build -t yogeshve1/complex-nginx ./nginx
    - docker build -t yogeshve1/complex-server ./server
    - docker build -t yogeshve1/complex-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push yogeshve1/complex-client
    - docker push yogeshve1/complex-nginx
    - docker push yogeshve1/complex-server
    - docker push yogeshve1/complex-worker

